LineageSettings: Validate settings before accepting them
* Instead of blindly accepting ANY value when set via shell, also validate
  values that come in via that way


device:/ # settings --lineage put system navigation_bar_hint 2

Exception occurred while executing:
java.lang.IllegalArgumentException: Invalid value: 2 for setting: navigation_bar_hint
	at org.lineageos.lineagesettings.LineageSettingsProvider.validateSystemSettingNameValue(LineageSettingsProvider.java:895)
	at org.lineageos.lineagesettings.LineageSettingsProvider.call(LineageSettingsProvider.java:341)
	at android.content.ContentProvider.call(ContentProvider.java:2152)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:477)
	at com.android.providers.settings.SettingsService$MyShellCommand.putForUser(SettingsService.java:429)
	at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:298)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:53)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

Change-Id: I7913545119fc9506a75b71bed800b67955065d07