Fix FindEmulator breakage due to missing dir
error: FindEmulator: find: `lineage-sdk/dummy': No such file or directory

Change-Id: I33712fa947432dcb6344ff9ceb1fa82e1e14a142