Update patch set 3
Patch Set 3:

I'm probably missing something completely obvious.  
But with a clean 15.0 repo with only angler in local manifest + this cherry-pick, I cannot get past the api with errors referring to support.v7


cm14.1 no problems and building reliably.  I have spent a couple days trying to find a proper work around, but figured it's time to ask.



lineage-sdk/sdk/src/java/lineageos/preference/ConstraintsHelper.java:27: error: package android.support.v7.preference does not exist
import android.support.v7.preference.Preference;

Patch-set: 3
Reviewer: DHO <5179@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Code-Review=0